### ISSUE TITLE
[PE-D][Tester B] Same name can be added, case insensitive 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W12-4/tp#179]
both John Doe and JOHN doe can be added (case insensitive), with the same exact details for everything else. Would make it difficult if there are 2 exact same persons.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: simbayippy/ped#1

**Comment by owenyeo** [comment]
Duplicate bug
