### ISSUE TITLE
[PE-D][Tester D] Example command doesn't work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W12-4/tp#180]
In the user guide, you provided an example command add n/John Doe p/98765432 t/johndoe e/johnd@example.com m/CS2103T /from 1200 /to 1300 /day Wednesday t/police

I tried to copy paste into the app and it said invalid command

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: tanveersingh10/ped#1

**Comment by owenyeo** [comment]
Duplicate
