### ISSUE TITLE
[PE-D][Tester C] Documentation: UG for add does not correspond to actual command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W12-4/tp#183]
Parameters for the add command in TimetaBRO differs from UG, which contains invalid prefixes such as m/, /start, /end, /day, etc.
Copying example from UG into TimetaBRO results in below:

![Screenshot 2023-11-03 at 4.17.59 PM.png](https://raw.githubusercontent.com/spatuly/ped/main/files/b0ab632c-f05e-4827-911f-e361238eba3c.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: spatuly/ped#1

**Comment by owenyeo** [comment]
Duplicate
