### ISSUE TITLE
[PE-D][Tester B] Doc error for List

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W12-4/tp#199]
I believe this might be because UG is incomplete, if so no worries about it then

![Screenshot 2023-11-03 at 4.34.59 PM.png](https://raw.githubusercontent.com/simbayippy/ped/main/files/1870badd-b3dc-4209-a651-82f1b2089bf3.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: simbayippy/ped#6

**Comment by owenyeo** [comment]
Duplicate
