### ISSUE TITLE
[PE-D][Tester D] Example commands in quick start are wrong

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W12-4/tp#208]
![Screenshot 2023-11-03 at 4.43.05 PM.png](https://raw.githubusercontent.com/tanveersingh10/ped/main/files/99821dfc-7408-43dc-ba31-3da6990c1046.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: tanveersingh10/ped#9

**Comment by owenyeo** [comment]
Not medium
