### ISSUE TITLE
[PE-D][Tester C] Functionality: unable to addschedule for modules with an end letter into TimetaBRO

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W12-4/tp#215]
An error message is shown when users attempt to add a module like CS2103T, CS2030S, which are all valid module codes in NUS. Maybe make the module name less restrictive? Perhaps also could take into account modules that begin with 3 letters, e.g. GEA1000, LSMxxxx, etc.

![Screenshot 2023-11-03 at 4.58.48 PM.png](https://raw.githubusercontent.com/spatuly/ped/main/files/4fbbdfb0-ac4e-4c9c-ba18-65c5fa66004f.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: spatuly/ped#7

**Comment by owenyeo** [comment]
Duplicate
