### ISSUE TITLE
[PE-D][Tester A] Cft command able to be entered without index

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W12-4/tp#216]
`cft` command seems to be able to work without index. It compares with the first member by default. Not a big issue though.

![image.png](https://raw.githubusercontent.com/WinSheng1/ped/main/files/283d32d4-6bf2-4a1b-a8d9-b67f148b85ae.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: WinSheng1/ped#7

**Comment by owenyeo** [comment]
Likely UG issue
