### ISSUE TITLE
[PE-D][Tester C] Functionality: rmschedule does not work on user

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W12-4/tp#218]
The rmschedule command does not work on user, despite valid inputs. Nothing occurs when the user tries to rmschedule on themselves. Error message is also not shown (no red text). Results in users being unable to remove any of the schedules they added for themselves - need to delete / edit the json file to do so.

![Screenshot 2023-11-03 at 5.06.41 PM.png](https://raw.githubusercontent.com/spatuly/ped/main/files/fbd3f00d-480c-4aea-9f27-ef4a6a41b26f.png)

Does not seem to be a problem with the duplication of cs2101 in the previous screenshot as resetting the data file, adding one schedule for user, then trying to rmschedule also results in the same problem, likely an issue with the implementation of rmschedule user?

![Screenshot 2023-11-03 at 5.12.33 PM.png](https://raw.githubusercontent.com/spatuly/ped/main/files/063cd490-e89d-454f-90ac-fd3d4a40f55c.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: spatuly/ped#8

**Comment by lululwtv** [comment]
This issue has been fixed
